from datetime import date

statements_old_team = [
    {
        "utterance": "Lenka is from Serbia",
        "subject": {"label": "lenka", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "serbia", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "piek",
        "chat": 1,
        "turn": 1,
        "position": "0-25",
        "date": date(2017, 10, 24)
    },
    {
        "utterance": "Bram is from the Netherlands",
        "subject": {"label": "bram", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "netherlands", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "piek",
        "chat": 1,
        "turn": 2,
        "position": "0-25",
        "date": date(2017, 10, 24)
    },
    {
        "utterance": "Selene is from Mexico",
        "subject": {"label": "selene", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "mexico", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "piek",
        "chat": 1,
        "turn": 3,
        "position": "0-25",
        "date": date(2017, 10, 24)
    },
    {
        "utterance": "Suzana is from Croatia",
        "subject": {"label": "suzana", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "croatia", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "piek",
        "chat": 1,
        "turn": 4,
        "position": "0-25",
        "date": date(2017, 10, 24)
    },
    {
        "utterance": "Selene Kolman is from the Netherlands",
        "subject": {"label": "selene-kolman", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "netherlands", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "piek",
        "chat": 1,
        "turn": 5,
        "position": "0-25",
        "date": date(2017, 10, 24)
    },
    {
        "utterance": "I think Lenka is from Serbia",
        "subject": {"label": "lenka", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "serbia", "type": "location"},
        "perspective": {"certainty": 0.5, "polarity": 1, "sentiment": 0},
        "author": "selene",
        "chat": 2,
        "turn": 1,
        "position": "0-25",
        "date": date(2017, 11, 17)
    },
    {
        "utterance": "Bram likes goulash",
        "subject": {"label": "bram", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "goulash", "type": "dish"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "selene",
        "chat": 2,
        "turn": 2,
        "position": "0-25",
        "date": date(2017, 11, 17)
    },
    {
        "utterance": "Bram likes romantic movies",
        "subject": {"label": "bram", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "romantic-movies", "type": "film-genre"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "selene",
        "chat": 2,
        "turn": 3,
        "position": "0-25",
        "date": date(2017, 11, 17)
    },
    {
        "utterance": "Lenka likes ice cream",
        "subject": {"label": "lenka", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "ice-cream", "type": "dish"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "selene",
        "chat": 2,
        "turn": 4,
        "position": "0-25",
        "date": date(2017, 11, 17)
    },
    {
        "utterance": "Lenka likes Harry Potter",
        "subject": {"label": "lenka", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "harry-potter", "type": "movie"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "selene",
        "chat": 2,
        "turn": 5,
        "position": "0-25",
        "date": date(2017, 11, 17)
    },
    {
        "utterance": "Lenka likes action movies",
        "subject": {"label": "lenka", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "action-movies", "type": "film-genre"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "selene",
        "chat": 2,
        "turn": 6,
        "position": "0-25",
        "date": date(2017, 11, 17)
    },
    {
        "utterance": "Piek likes balkenbrij",
        "subject": {"label": "piek", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "balkenbrij", "type": "dish"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "selene",
        "chat": 2,
        "turn": 7,
        "position": "0-25",
        "date": date(2017, 11, 17)
    },
    {
        "utterance": "Piek likes sailing",
        "subject": {"label": "piek", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "sailing", "type": "sport"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "selene",
        "chat": 2,
        "turn": 8,
        "position": "0-25",
        "date": date(2017, 11, 17)
    },
    {
        "utterance": "I like tacos",
        "subject": {"label": "selene", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "tacos", "type": "dish"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "selene",
        "chat": 2,
        "turn": 9,
        "position": "0-25",
        "date": date(2017, 11, 17)
    },
    {
        "utterance": "Suzana likes pizza",
        "subject": {"label": "suzana", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "pizza", "type": "dish"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "selene",
        "chat": 2,
        "turn": 10,
        "position": "0-25",
        "date": date(2017, 11, 17)
    },
    {
        "utterance": "Leolani is from France",
        "subject": {"label": "leolani", "type": "robot"},
        "predicate": {"type": "be-from"},
        "object": {"label": "france", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "selene",
        "chat": 2,
        "turn": 11,
        "position": "0-25",
        "date": date(2017, 11, 17)
    },
    {
        "utterance": "Lenka's mother is Ljubica ",
        "subject": {"type": "person", "label": "lenka"},
        "predicate": {"type": "mother-is"},
        "object": {"type": "person", "label": "ljubica"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "lenka",
        "chat": 3,
        "turn": 1,
        "position": "0-25",
        "date": date(2018, 3, 20)
    },
    {
        "utterance": "My favorite food is cake ",
        "subject": {"type": "person", "label": "lenka"},
        "predicate": {"type": "favorite-is"},
        "object": {"type": "dish", "label": "cake"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "lenka",
        "chat": 3,
        "turn": 2,
        "position": "0-25",
        "date": date(2018, 3, 20)
    },
    {
        "utterance": "Selene likes Coco",
        "subject": {"label": "selene", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "coco", "type": "movie"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "lenka",
        "chat": 3,
        "turn": 3,
        "position": "0-25",
        "date": date(2018, 3, 20)
    },
    {
        "utterance": "Bram likes The Big Lebowski",
        "subject": {"label": "bram", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "the_big-lebowski", "type": "movie"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "lenka",
        "chat": 3,
        "turn": 4,
        "position": "0-25",
        "date": date(2018, 3, 20)
    },
    {
        "utterance": "Piek likes 2001 A Space Odyssey",
        "subject": {"label": "piek", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "2001_a_space-odyssey", "type": "movie"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "lenka",
        "chat": 3,
        "turn": 5,
        "position": "0-25",
        "date": date(2018, 3, 20)
    },
    {
        "utterance": "Piek likes horror movies",
        "subject": {"label": "piek", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "horror-movies", "type": "film-genre"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "lenka",
        "chat": 3,
        "turn": 6,
        "position": "0-25",
        "date": date(2018, 3, 20)
    },
    {
        "utterance": "I like action movies ",
        "subject": {"type": "person", "label": "bram"},
        "predicate": {"type": "like"},
        "object": {"type": "film-genre", "label": "action-movies"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "bram",
        "chat": 4,
        "turn": 1,
        "position": "0-25",
        "date": date(2018, 3, 23)
    },
    {
        "utterance": "I am from Italy ",
        "subject": {"type": "person", "label": "bram"},
        "predicate": {"type": "be-from"},
        "object": {"type": "location", "label": "italy"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "bram",
        "chat": 4,
        "turn": 2,
        "position": "0-25",
        "date": date(2018, 3, 23)
    },
    {
        "utterance": "I do not like goulash",
        "subject": {"label": "bram", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "goulash", "type": "dish"},
        "perspective": {"certainty": 1, "polarity": -1, "sentiment": -1},
        "author": "bram",
        "chat": 4,
        "turn": 3,
        "position": "0-21",
        "date": date(2018, 3, 23)
    },
    {
        "utterance": "I like baseball",
        "subject": {"label": "bram", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "baseball", "type": "sport"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "bram",
        "chat": 4,
        "turn": 4,
        "position": "0-25",
        "date": date(2018, 3, 23)
    },
    {
        "utterance": "I like apple pie",
        "subject": {"label": "bram", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "apple-pie", "type": "dish"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "bram",
        "chat": 4,
        "turn": 5,
        "position": "0-25",
        "date": date(2018, 3, 23)
    },
    {
        "utterance": "Selene likes animated movies",
        "subject": {"label": "selene", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "animated-movies", "type": "film-genre"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "bram",
        "chat": 4,
        "turn": 6,
        "position": "0-25",
        "date": date(2018, 3, 23)
    },
    {
        "utterance": "Lenka likes acrobatics",
        "subject": {"label": "lenka", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "acrobatics", "type": "sport"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "bram",
        "chat": 4,
        "turn": 7,
        "position": "0-25",
        "date": date(2018, 3, 23)
    },
    {
        "utterance": "Leolani is from Japan",
        "subject": {"label": "leolani", "type": "robot"},
        "predicate": {"type": "be-from"},
        "object": {"label": "japan", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "bram",
        "chat": 4,
        "turn": 8,
        "position": "0-25",
        "date": date(2018, 3, 23)
    },
    {
        "utterance": "Bram likes romantic movies",
        "subject": {"type": "person", "label": "bram"},
        "predicate": {"type": "like"},
        "object": {"type": "film-genre", "label": "romantic-movies"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "piek",
        "chat": 5,
        "turn": 1,
        "position": "0-25",
        "date": date(2018, 3, 25)
    },
    {
        "utterance": "Selene does not like tacos",
        "subject": {"label": "selene", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "tacos", "type": "dish"},
        "perspective": {"certainty": 1, "polarity": -1, "sentiment": -1},
        "author": "piek",
        "chat": 5,
        "turn": 2,
        "position": "0-26",
        "date": date(2018, 3, 25)
    },
    {
        "utterance": "I hate tacos",
        "subject": {"label": "piek", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "tacos", "type": "dish"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": -1},
        "author": "piek",
        "chat": 5,
        "turn": 3,
        "position": "0-12",
        "date": date(2018, 3, 25)
    },
    {
        "utterance": "Bram is not from the Netherlands",
        "subject": {"label": "bram", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "netherlands", "type": "location"},
        "perspective": {"certainty": 1, "polarity": -1, "sentiment": 0},
        "author": "suzana",
        "chat": 6,
        "turn": 1,
        "position": "0-25",
        "date": date(2019, 3, 19)
    },
    {
        "utterance": "Piek is from the Netherlands",
        "subject": {"label": "piek", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "netherlands", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "suzana",
        "chat": 6,
        "turn": 2,
        "position": "0-25",
        "date": date(2019, 3, 19)
    },
    {
        "utterance": "Selene likes soccer",
        "subject": {"label": "selene", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "soccer", "type": "sport"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "suzana",
        "chat": 6,
        "turn": 3,
        "position": "0-25",
        "date": date(2019, 3, 19)
    },
    {
        "utterance": "Bram knows Lenka",
        "subject": {"label": "bram", "type": "person"},
        "predicate": {"type": "know"},
        "object": {"label": "lenka", "type": "person"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "suzana",
        "chat": 6,
        "turn": 4,
        "position": "0-16",
        "date": date(2019, 3, 19)
    },
    {
        "utterance": "Selene knows Lenka",
        "subject": {"label": "selene", "type": "person"},
        "predicate": {"type": "know"},
        "object": {"label": "lenka", "type": "person"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "suzana",
        "chat": 6,
        "turn": 5,
        "position": "0-16",
        "date": date(2019, 3, 19)
    },
    {
        "utterance": "I think Selene is from Peru",
        "subject": {"label": "selene", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "peru", "type": "location"},
        "perspective": {"certainty": 0.5, "polarity": 1, "sentiment": 0},
        "author": "lenka",
        "chat": 7,
        "turn": 1,
        "position": "0-27",
        "date": date(2020, 7, 19)
    }
]

statements_new_team = [
    {
        "utterance": "Jaap has three teapots",
        "subject": {"label": "jaap", "type": "person"},
        "predicate": {"type": "have"},
        "object": {"label": "teapot", "type": "artefact"},
        "perspective": {"certainty": 0.75, "polarity": 1, "sentiment": 0},
        "author": "lea",
        "chat": 8,
        "turn": 1,
        "position": "0-22",
        "date": date(2020, 9, 19)
    },
    {
        "utterance": "My favourite colour is blue",
        "subject": {"label": "lea", "type": "person"},
        "predicate": {"type": "favorite-color-is"},
        "object": {"label": "blue", "type": "adj.all"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "lea",
        "chat": 8,
        "turn": 2,
        "position": "0-27",
        "date": date(2020, 9, 19)
    },
    {
        "utterance": "I think Selene is tall",
        "subject": {"label": "selene", "type": "person"},
        "predicate": {"type": "be"},
        "object": {"label": "tall", "type": "adj.all"},
        "perspective": {"certainty": 0.4, "polarity": 1, "sentiment": 0},
        "author": "lea",
        "chat": 8,
        "turn": 3,
        "position": "0-22",
        "date": date(2020, 9, 19)
    },
    {
        "utterance": "I like swimming and biking",
        "subject": {"label": "lea", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "swimming-and-biking", "type": "act"},
        "perspective": {"certainty": 0.8, "polarity": 1, "sentiment": 1},
        "author": "lea",
        "chat": 8,
        "turn": 4,
        "position": "0-26",
        "date": date(2020, 9, 19)
    },
    {
        "utterance": "I'm from Dusseldorf",
        "subject": {"label": "lea", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "dusseldorf", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "lea",
        "chat": 8,
        "turn": 5,
        "position": "0-27",
        "date": date(2020, 9, 19)
    },
    {
        "utterance": "I don't like celery",
        "subject": {"label": "lea", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "celery", "type": "food"},
        "perspective": {"certainty": 0.9, "polarity": -1, "sentiment": -1},
        "author": "lea",
        "chat": 8,
        "turn": 6,
        "position": "0-19",
        "date": date(2020, 9, 19)
    },
    {
        "utterance": "I live in Berlin",
        "subject": {"label": "thomas", "type": "person"},
        "predicate": {"type": "live-in"},
        "object": {"label": "berlin", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "thomas",
        "chat": 9,
        "turn": 1,
        "position": "0-26",
        "date": date(2020, 9, 21)
    },
    {
        "utterance": "I am from Munich",
        "subject": {"label": "thomas", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "munich", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "thomas",
        "chat": 9,
        "turn": 2,
        "position": "0-16",
        "date": date(2020, 9, 21)
    },
    {
        "utterance": "I studied in Budapest",
        "subject": {"label": "thomas", "type": "person"},
        "predicate": {"type": "study-in"},
        "object": {"label": "budapest", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "thomas",
        "chat": 9,
        "turn": 3,
        "position": "0-21",
        "date": date(2020, 9, 21)
    },
    {
        "utterance": "I like Asian food",
        "subject": {"label": "thomas", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "asian-food", "type": "cuisine"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "thomas",
        "chat": 9,
        "turn": 4,
        "position": "0-17",
        "date": date(2020, 9, 21)
    },
    {
        "utterance": "I like electronic music",
        "subject": {"label": "thomas", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "electronic-music", "type": "music"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "thomas",
        "chat": 9,
        "turn": 5,
        "position": "0-23",
        "date": date(2020, 9, 21)
    },
    {
        "utterance": "I think Lea hates cheese",
        "subject": {"label": "lea", "type": "person"},
        "predicate": {"type": "hate"},
        "object": {"label": "cheese", "type": "food"},
        "perspective": {"certainty": 0.6, "polarity": 1, "sentiment": -1},
        "author": "jaap",
        "chat": 10,
        "turn": 1,
        "position": "0-25",
        "date": date(2020, 9, 24)
    },
    {
        "utterance": "Selene likes dancing",
        "subject": {"label": "selene", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "dancing", "type": "act"},
        "perspective": {"certainty": 0.8, "polarity": 1, "sentiment": 1},
        "author": "jaap",
        "chat": 10,
        "turn": 2,
        "position": "0-20",
        "date": date(2020, 9, 24)
    },
    {
        "utterance": "I have two teapots",
        "subject": {"label": "jaap", "type": "person"},
        "predicate": {"type": "have"},
        "object": {"label": "two-teapots", "type": "artifact"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "jaap",
        "chat": 10,
        "turn": 3,
        "position": "0-18",
        "date": date(2020, 9, 24)
    },
    {
        "utterance": "I don't like chocolate with sea salt",
        "subject": {"label": "jaap", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "chocolate-with-sea-salt", "type": "food"},
        "perspective": {"certainty": 1, "polarity": -1, "sentiment": 0},
        "author": "jaap",
        "chat": 10,
        "turn": 4,
        "position": "0-36",
        "date": date(2020, 9, 24)
    },
    {
        "utterance": "I think Lea likes swimming and vikings",
        "subject": {"label": "lea", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "swimming-and-vikings", "type": "act"},
        "perspective": {"certainty": 0.2, "polarity": 1, "sentiment": 1},
        "author": "jaap",
        "chat": 10,
        "turn": 5,
        "position": "0-38",
        "date": date(2020, 9, 24)
    },
    {
        "utterance": "Tae speaks German",
        "subject": {"label": "tae", "type": "person"},
        "predicate": {"type": "speak"},
        "object": {"label": "german", "type": "adj.all"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "jaap",
        "chat": 10,
        "turn": 6,
        "position": "0-17",
        "date": date(2020, 9, 24)
    },
    {
        "utterance": "I like drinking beer",
        "subject": {"label": "tae", "type": "person"},
        "predicate": {"type": "like"},
        "object": {"label": "drinking-beer", "type": "interest"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 1},
        "author": "tae",
        "chat": 11,
        "turn": 1,
        "position": "0-20",
        "date": date(2020, 9, 29)
    },
    {
        "utterance": "I am from South Korea",
        "subject": {"label": "tae", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {"label": "south-korea", "type": "location"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "tae",
        "chat": 11,
        "turn": 2,
        "position": "0-21",
        "date": date(2020, 9, 29)
    },
    {
        "utterance": "I ride a bike",
        "subject": {"label": "tae", "type": "person"},
        "predicate": {"type": "ride"},
        "object": {"label": "bike", "type": "transportation"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "tae",
        "chat": 11,
        "turn": 3,
        "position": "0-13",
        "date": date(2020, 9, 29)
    },
    {
        "utterance": "I hate rats",
        "subject": {"label": "Tae", "type": "person"},
        "predicate": {"type": "hate"},
        "object": {"label": "rats", "type": "animal"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": -1},
        "author": "tae",
        "chat": 11,
        "turn": 4,
        "position": "0-11",
        "date": date(2020, 9, 29)
    },
    {
        "utterance": "I do not drink beer",
        "subject": {"label": "tae", "type": "person"},
        "predicate": {"type": "drink"},
        "object": {"label": "drinking-beer", "type": "interest"},
        "perspective": {"certainty": 1, "polarity": -1, "sentiment": 0},
        "author": "tae",
        "chat": 11,
        "turn": 5,
        "position": "0-19",
        "date": date(2020, 9, 29)
    }
]

statements = statements_old_team + statements_new_team

questions = [
    {
        "predicate": {"type": "be-from"},
        "chat": 0,
        "author": "jo",
        "object": {"type": "", "label": ""},
        "turn": 7, "utterance_type": "question",
        "date": "",
        "position": "",
        "subject": {"type": "", "label": "bram"}},
    {
        "utterance": "Who is from the Serbia?",
        "subject": {"label": "", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {
            "label": "serbia",
            "type": "location"
        }
    },
    {
        "utterance": "Where is Lenka from?",
        "subject": {"label": "lenka", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {
            "label": "",
            "type": "location"
        }
    },
    {  # Does selene know piek?
        "subject": {"label": "selene", "type": "person"},
        "predicate": {"type": "knows"},
        "object": {
            "label": "piek",
            "type": "person"
        }
    },
    {
        "utterance": "Is Bram from the Netherlands?",
        "subject": {"label": "bram", "type": "person"},
        "predicate": {"type": "be-from"},
        "object": {
            "label": "netherlands",
            "type": "location"
        }
    },
    {
        "utterance": "Does Bram know Beyonce?",
        "predicate":
            {"type": "knows"},
        "chat": "",
        "author": "person",
        "object": {"type": "", "label": "beyonce"},
        "turn": "",
        "utterance_type": "question",
        "date": date(2018, 3, 19),
        "position": "",
        "subject": {"type": "person", "label": "bram"}
    },
    {
        "utterance": "Do you know Bram?",
        "predicate": {"type": "knows"}, "chat": "", "author": "bram",
        "object": {"type": "person", "label": "bram"}, "turn": "",
        "utterance_type": "question",
        "date": date(2018, 3, 19), "position": "", "response": {"role": "", "format": ""},
        "subject": {"type": "robot", "label": "leolani"}
    },
    {
        "utterance": "Does Selene know Piek?",
        "predicate": {"type": "knows"}, "chat": "", "author": "person",
        "object": {"type": "person", "label": "piek"}, "turn": "",
        "utterance_type": "question",
        "date": date(2018, 3, 19), "position": "", "response": {"role": "", "format": ""},
        "subject": {"type": "person", "label": "selene"}
    },
    {
        "utterance": "Where is Leolani from?",
        "predicate": {"type": "be-from"}, "chat": "", "author": "person",
        "object": {"type": "", "label": ""}, "turn": "", "utterance_type": "question",
        "date": date(2018, 3, 19), "position": "", "response": {"role": "", "format": ""},
        "subject": {"type": "robot", "label": "leolani"}
    },
    {
        "utterance": "Who is from italy?",
        "predicate": {"type": "be-from"}, "chat": "", "author": "jill",
        "object": {"type": "", "label": "italy"}, "turn": "", "utterance_type": "question",
        "date": date(2018, 3, 19), "position": "", "response": {"role": "", "format": ""},
        "subject": {"type": "", "label": ""}
    },
    {
        "utterance": "what does Piek like?",
        "predicate": {"type": "like"},
        "chat": "",
        "author": "jo",
        "object": {"type": "", "label": ""},
        "turn": "",
        "utterance_type": "question",
        "date": date(2018, 3, 19),
        "position": "",
        "subject": {"type": "", "label": "piek"}
    }
]

experiences = [
    {  # Leolani saw an apple
        "subject": {"label": "", "type": ""},
        "predicate": {"type": ""},
        "object": {"label": "apple", "type": "fruit"},
        "perspective": {"certainty": 1, "polarity": 1, "sentiment": 0},
        "author": "front_camera",
        "chat": None,
        "turn": None,
        "position": "0-15-0-15",
        "date": date(2018, 3, 19)
    }
]

visuals = [
    ['tv', "carpenter's kit", 'tool kit'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['potted plant', 'pot', 'flowerpot'],
    ['laptop', 'laptop', 'laptop computer'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['laptop', 'laptop', 'laptop computer'],
    ['laptop', 'laptop', 'laptop computer'],
    ['laptop', 'laptop', 'laptop computer'],
    ['laptop', 'laptop', 'laptop computer'],
    ['laptop', 'laptop', 'laptop computer'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['potted plant', 'pot', 'flowerpot'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['laptop', 'notebook', 'notebook computer'],
    ['chair', 'desk'],
    ['laptop', 'notebook', 'notebook computer'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['laptop', 'notebook', 'notebook computer'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['laptop', 'printer'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['laptop', 'notebook', 'notebook computer'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['laptop', 'notebook', 'notebook computer'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['laptop', 'notebook', 'notebook computer'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['laptop', 'notebook', 'notebook computer'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', 'espresso maker'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', 'espresso maker'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', 'espresso maker'],
    ['tv', 'espresso maker'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', 'espresso maker'],
    ['tv', 'espresso maker'],
    ['tv', 'espresso maker'],
    ['tv', 'espresso maker'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', 'espresso maker'],
    ['tv', 'espresso maker'],
    ['tv', 'espresso maker'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', 'espresso maker'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', 'espresso maker'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['chair', 'desk'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', 'espresso maker'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', "potter's wheel"],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', "potter's wheel"],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', 'espresso maker'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['tv', 'espresso maker'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', "potter's wheel"],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', 'pay-phone', 'pay-station'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['tv', 'espresso maker'],
    ['tv', 'pay-phone', 'pay-station'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', "potter's wheel"],
    ['tv', "carpenter's kit", 'tool kit'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', "potter's wheel"],
    ['tv', "carpenter's kit", 'tool kit'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['potted plant', 'pot', 'flowerpot'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['tv', "carpenter's kit", 'tool kit'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['chair', 'desk'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['potted plant', 'pot', 'flowerpot'],
    ['laptop', 'notebook', 'notebook computer'],
    ['chair', 'desk']
]

sample_coco = ['Bag', 'backpack', 'handbag', 'suitcase', 'umbrella', 'tie', 'Animal', 'bird', 'cat', 'dog', 'horse',
               'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'Food', 'banana', 'apple', 'orange', 'carrot',
               'broccoli', 'cake', 'pizza', 'hot dog', 'donut', 'sandwich', 'Sports', 'tennis racket',
               'badminton racket', 'baseball bat', 'kite', 'snowboard', 'ball', 'basketball', 'Furniture', 'chair',
               'sofa', 'bed', 'toilet', 'couch', 'fridge', 'Office', 'keyboard', 'mouse', 'cellphone', 'tv', 'laptop',
               'Miscellaneous', 'Book', 'clock']
