PREFIX eps: <http://cltl.nl/episodicawareness/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT ?cl ?pl ?date (GROUP_CONCAT(?sl;separator="|") as ?detections)
WHERE {
    ?c eps:hasDetection ?s .
    ?c rdfs:label ?cl .
    ?s rdfs:label ?sl .
    ?c sem:hasPlace ?p  .
    ?p rdfs:label ?pl .
    ?c sem:hasBeginTimeStamp ?t .
    ?t rdfs:label ?date .
} group by ?cl ?pl ?date
