PREFIX eps: <http://cltl.nl/episodicawareness/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX n2mu: <http://cltl.nl/leolani/n2mu/>
PREFIX leolaniContext: <http://cltl.nl/leolani/context/>

SELECT ?type  (GROUP_CONCAT(DISTINCT ?si;separator="|") as ?ids) (GROUP_CONCAT( ?num_observation;separator="|") as ?imp)
WHERE {

SELECT ?si  (COUNT(DISTINCT ?c) as ?num_observation)   (GROUP_CONCAT(DISTINCT ?stob;separator="|") as ?type)
WHERE {
    ?c eps:hasDetection ?s .
    ?s n2mu:id ?si .
    ?s rdf:type n2mu:object, ?st, ?stob .
    FILTER(regex(str(?stob), "n2mu")) .
    FILTER(regex(str(?st), "n2mu")) .
    FILTER(!regex(str(?stob), "object")) .
    ?c sem:hasPlace leolaniContext:%s  .
}
group by ?si
    order by DESC(COUNT(DISTINCT ?c))
}
group by ?type
