prefix grasp: <http://groundedannotationframework.org/grasp#>
SELECT ?type ?s ?p ?o ?v ?author

WHERE {
GRAPH ?g { ?s ?p ?o . }
?s rdf:type ?type .
?g grasp:denotedBy ?m .
?a grasp:isAttributionFor ?m .
?a rdf:value ?v .
?a grasp:wasDerivedFrom ?turn .
?turn prov:wasAttributedTo ?author .
}