PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX n2mu: <http://cltl.nl/leolani/n2mu/>


select distinct ?name (count(distinct ?chat) as ?num_chat) where {
    ?act rdf:type sem:Actor .
    ?act rdf:type n2mu:person .
    ?act rdfs:label ?name .
    ?chat sem:hasActor ?act

    MINUS {  VALUES (?name) { ('stranger') ('human')} }

}    GROUP BY ?name
ORDER BY DESC (?num_chat)
LIMIT 5