from .brain import BrainComponent
from .camera import CameraComponent
from .face_detection import FaceDetectionComponent
from .object_detection import ObjectDetectionComponent, ObjectDetectionTarget
from .text_to_speech import TextToSpeechComponent
from .speech_recognition import StreamedSpeechRecognitionComponent, SynchronousSpeechRecognitionComponent
from .statistics import StatisticsComponent
