PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select distinct ?l ?o where {
            ?s a ?o .
    		?s rdfs:label ?l
            FILTER(regex(str(?o), "n2mu")) .
        } ORDER BY (str(?p))