PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX grasp: <http://groundedannotationframework.org/grasp#>
PREFIX n2mu: <http://cltl.nl/leolani/n2mu/>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX time: <http://www.w3.org/TR/owl-time/#>

select ?chatid ?day ?month ?year where {
    ?chat rdf:type grasp:Chat .
    ?chat n2mu:id ?chatid .
    ?chat sem:hasActor ?actor .
    ?actor rdfs:label "%s" .
    ?chat sem:hasTime ?time .
    ?time time:day ?day .
    ?time time:month ?month .
    ?time time:year ?year .
    FILTER(!regex(str(?chat), "turn")) .
} ORDER BY DESC (?chat)
LIMIT 1