PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX grasp: <http://groundedannotationframework.org/grasp#>
PREFIX n2mu: <http://cltl.nl/leolani/n2mu/>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>

select ?turnid where {
    ?chat rdf:type grasp:Chat .
    ?chat n2mu:id "%s" .
    ?chat sem:hasSubevent ?turn .
    ?turn n2mu:id ?turnid .
} ORDER BY DESC (?turnid)
LIMIT 1