
sensed = [
    {  # Leolani saw an apple
        "subject": {
            "label": "",
            "type": ""
        },
        "predicate": {
            "type": ""
        },
        "object": {
            "label": "apple",
            "type": "Fruit"
        },
        "author": "",
        "chat": None,
        "turn": None,
        "position": "",
        "date": None #date.today()
    }
]

VISUALS = [
['tv', "carpenter's kit", 'tool kit'],
['tv', "carpenter's kit", 'tool kit'],
['potted plant', 'pot', 'flowerpot'],
['laptop', 'laptop', 'laptop computer'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['laptop', 'laptop', 'laptop computer'],
['laptop', 'laptop', 'laptop computer'],
['laptop', 'laptop', 'laptop computer'],
['laptop', 'laptop', 'laptop computer'],
['laptop', 'laptop', 'laptop computer'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['tv', "carpenter's kit", 'tool kit'],
['potted plant', 'pot', 'flowerpot'],
['chair', 'desk'],
['chair', 'desk'],
['laptop', 'notebook', 'notebook computer'],
['chair', 'desk'],
['laptop', 'notebook', 'notebook computer'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['laptop', 'notebook', 'notebook computer'],
['chair', 'desk'],
['chair', 'desk'],
['laptop', 'printer'],
['chair', 'desk'],
['chair', 'desk'],
['laptop', 'notebook', 'notebook computer'],
['chair', 'desk'],
['chair', 'desk'],
['laptop', 'notebook', 'notebook computer'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['laptop', 'notebook', 'notebook computer'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['laptop', 'notebook', 'notebook computer'],
['potted plant', 'pot', 'flowerpot'],
['tv', "carpenter's kit", 'tool kit'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['tv', 'espresso maker'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['tv', 'espresso maker'],
['potted plant', 'pot', 'flowerpot'],
['tv', 'espresso maker'],
['tv', 'espresso maker'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['tv', "carpenter's kit", 'tool kit'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['tv', 'espresso maker'],
['tv', 'espresso maker'],
['tv', 'espresso maker'],
['tv', 'espresso maker'],
['potted plant', 'pot', 'flowerpot'],
['tv', 'espresso maker'],
['tv', 'espresso maker'],
['tv', 'espresso maker'],
['potted plant', 'pot', 'flowerpot'],
['tv', "carpenter's kit", 'tool kit'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['tv', 'espresso maker'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['tv', 'espresso maker'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['chair', 'desk'],
['tv', "carpenter's kit", 'tool kit'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['tv', 'espresso maker'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', "potter's wheel"],
['potted plant', 'pot', 'flowerpot'],
['potted plant', "potter's wheel"],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['tv', 'espresso maker'],
['potted plant', 'pot', 'flowerpot'],
['tv', "carpenter's kit", 'tool kit'],
['tv', 'espresso maker'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['tv', "carpenter's kit", 'tool kit'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', "potter's wheel"],
['potted plant', 'pot', 'flowerpot'],
['tv', 'pay-phone', 'pay-station'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['tv', "carpenter's kit", 'tool kit'],
['tv', "carpenter's kit", 'tool kit'],
['tv', "carpenter's kit", 'tool kit'],
['tv', "carpenter's kit", 'tool kit'],
['tv', 'espresso maker'],
['tv', 'pay-phone', 'pay-station'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', "potter's wheel"],
['tv', "carpenter's kit", 'tool kit'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', "potter's wheel"],
['tv', "carpenter's kit", 'tool kit'],
['potted plant', 'pot', 'flowerpot'],
['tv', "carpenter's kit", 'tool kit'],
['potted plant', 'pot', 'flowerpot'],
['tv', "carpenter's kit", 'tool kit'],
['tv', "carpenter's kit", 'tool kit'],
['tv', "carpenter's kit", 'tool kit'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['chair', 'desk'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['potted plant', 'pot', 'flowerpot'],
['laptop', 'notebook', 'notebook computer'],
['chair', 'desk']
]