PREFIX leolaniWorld: <http://cltl.nl/leolani/world/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?type where {
	leolaniWorld:%s rdf:type ?type .
    FILTER(regex(str(?type), "n2mu")) .
}
