SELECT ?item ?itemLabel ?itemtype ?itemtypeLabel ?itemDescription
WHERE {
  ?item rdfs:label ?itemLabel.
  FILTER((LCASE(?itemLabel) = "%s"@en)).
  OPTIONAL{?item wdt:P31 ?itemtype . }
  OPTIONAL {?itemtype rdfs:label ?itemtypeLabel . }
  FILTER(LANG(?itemtypeLabel) in ("en")) .
  OPTIONAL {?item schema:description ?itemDescription.}
} limit 1