PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX grasp: <http://groundedannotationframework.org/grasp#>
PREFIX gaf: <http://groundedannotationframework.org/gaf#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>

select (COUNT(?stat) AS ?num_stat) where {
?stat rdf:type gaf:Assertion .
?stat gaf:denotedBy ?m .
?m grasp:wasAttributedTo ?author .
?author rdfs:label "%s" .
}