PREFIX n2mu: <http://cltl.nl/leolani/n2mu/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gaf: <http://groundedannotationframework.org/gaf#>

select ?slabel ?trust where {
	?s n2mu:hasTrustworthinessLevel ?trust .
    ?s rdfs:label ?slabel .
    ?s rdf:type gaf:Instance .

    FILTER (?slabel = "%s" )
} GROUP BY ?slabel ?trust
